//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LC.ReadWriteSecurity {
    
    
    public partial class ReadWriteSecurity {
        
        /// <summary>
        /// FormattedStringWithListType2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Microsoft.SharePoint.WebControls.FormattedStringWithListType FormattedStringWithListType2;
        
        /// <summary>
        /// FormattedStringWithListType1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Microsoft.SharePoint.WebControls.FormattedStringWithListType FormattedStringWithListType1;

        protected global::Microsoft.SharePoint.WebControls.InputFormSection AllowCrawlSection;
        protected global::System.Web.UI.WebControls.Button BtnSaveAdvancedSettings;
        protected global::System.Web.UI.WebControls.PlaceHolder ItemLevelSecurityPanel;
        protected global::Microsoft.SharePoint.WebControls.InputFormSection ItemLevelSecuritySection;
        protected global::System.Web.UI.WebControls.RadioButton RadReadSecurityAll;
        protected global::System.Web.UI.WebControls.RadioButton RadReadSecurityOwn;
        protected global::System.Web.UI.WebControls.RadioButton RadWriteSecurityAll;
        protected global::System.Web.UI.WebControls.RadioButton RadWriteSecurityNone;
        protected global::System.Web.UI.WebControls.RadioButton RadWriteSecurityOwn;

        protected global::Microsoft.SharePoint.WebControls.ButtonSection okCancelButtonSection;
    }
}
